name: .NET Core

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    env:
      working-directory: apis/poi/web

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: show folder
      run: pwd
    - working-directory: ${{env.working-directory}}
    - name: Install dependencies
      run: dotnet restore
    - working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore apis/poi/poi.sln
    - working-directory: ${{env.working-directory}} 
      name: Test
      run: dotnet test --no-restore --verbosity normal

